### ISSUE TITLE
Entity/Link/Action attribute manipulation

### ISSUE THREAD

**Issue by cha55son** [cha55son/siren_client#3]
Does anyone have a use-case where they would like to be able to change the `.href` of an entity, link, or action? 

For instance if there happens to be out of band information in the API and you need to add something on to the url? Let's say the action's `.href` is `http://example.com/api/messages`. But for some reason you need to edit the `.href` to look like `http://example.com/api/example/message`.

**Comment by apsoto** [comment]
Only use case I have is to add query parameters.

**Comment by cha55son** [comment]
If you need to add additional query parameters you can do that by supplying the extra params to the `action.where(param1: 'test', param2: 'test2')`.
